# Generated by Django 4.2 on 2023-05-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HtmlTeplates',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Subject', models.CharField(max_length=50)),
                ('htmlEncoded', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='subscribeDate',
            field=models.CharField(default='14020214', max_length=8),
        ),
    ]
