version: '3.3'

services:
  backend:
    build:
      context: ./MESS
    container_name: MESS_backend
    command: gunicorn MESS.wsgi --bind 0.0.0.0:8000
    # ports:
    #   - 8000:8000
    volumes:
      - /root/services/METAVA_ESS/MESS:/var/lib/metavadb
    restart: on-failure:5

  nginx:
    image: nginx:1.23.4 
    container_name: MESS_nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/build:/var/www/react
    depends_on:
      - backend
    restart: on-failure:5

volumes:
  react_build:
