import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

port = 587
smtp_server = "mail.srbiau.ac.ir"
login = "ma.farahbakhsh@srbiau.ac.ir" # paste your login generated by Mailtrap
password = "Fsh@2022" # paste your password generated by Mailtrap

def sendMail(receiver_email,Subject,html):
    sender_email = "ma.farahbakhsh@srbiau.ac.ir"
    receiver_email = receiver_email
    Subject= Subject
    html = html


    message = MIMEMultipart("alternative")
    message["Subject"] = Subject
    message["From"] = sender_email
    message["To"] = receiver_email

    part2 = MIMEText(html, "html")
    message.attach(part2)

    with smtplib.SMTP(smtp_server, port) as server:
        server.login(login, password)
        server.sendmail(
            sender_email, receiver_email, message.as_string()
        )

    return True